name: Release

on:
  workflow_run:
    workflows:
      - Build app
    types:
      - completed

jobs:
  build-success:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate release notes
        run: pnpx changelogithub@15.0.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-failure:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Build workflow failed'
