name: Release

on:
  workflow_run:
    workflows:
      - Build app
    types:
      - completed

jobs:
  build-success:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Setup Node.js LTS
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: lts/*

      - name: Generate release notes
        run: npx changelogithub@15.0.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-failure:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Build workflow failed'
